# Generated by Django 3.0.8 on 2021-03-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_clientstable_studentmark_studentprofile_testdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientsTable',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='studentMark',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TestDetails',
        ),
    ]
